### ISSUE TITLE
bash to do the same thing

### ISSUE THREAD

**Issue by mdave16** [mefellows/sitemap-generator#5]
under alternatives, you start with `wget`, i think you mean something along the lines of 

```
wget --spider --recursive --no-verbose --output-file=wgetlog.txt http://somewebsite.com
sed -n "s@.\+ URL:\([^ ]\+\) .\+@\1@p" wgetlog.txt | sed "s@&@\&amp;@" > sedlog.txt
```

source: https://stackoverflow.com/questions/3948947/can-i-use-wget-to-generate-a-sitemap-of-a-website-given-its-url

it could be further tweaked to create a one-liner, but i'm not sure how. I realise this is like 3 years too late, but thought it might be worthwhile for the readme?

**Comment by mefellows** [comment]
haha thanks @mdave16. I'll update :)
